### PR TITLE
Add compiler warnings

### PR DESCRIPTION
**Pull request by Ondraceq**

### CODE REVIEW

**Comment by Ondraceq** [comment]
It seems as cxxopts has `-Werror` flag set which collides with the `-Wconversion` flag that I wanted to enable.

**Comment by yaqwsx** [comment]
You can add `Wno-conversion` just for cxxopts.

**Comment by yaqwsx** [comment]
This works well:
```
diff --git a/suites/desktop/CMakeLists.txt b/suites/desktop/CMakeLists.txt
index d071d39..0117a76 100644
--- a/suites/desktop/CMakeLists.txt
+++ b/suites/desktop/CMakeLists.txt
@@ -112,6 +112,7 @@ FetchContent_GetProperties(cxxopts)
 if(NOT cxxopts_POPULATED)
   FetchContent_Populate(cxxopts)
   add_subdirectory(${cxxopts_SOURCE_DIR} ${cxxopts_BINARY_DIR})
+  target_compile_options(cxxopts INTERFACE "-Wno-conversion")
 endif()
```

**Comment by Ondraceq** [comment]
I found out that the problem is that `cxxopts` by default compiles its' tests and example and does this with added `-Werror`.

It can be opt-out of the compilation by setting `CXXOPTS_BUILD_EXAMPLES` and `CXXOPTS_BUILD_TESTS` to `OFF`. (See c48b3fc for the solution).

**Review by yaqwsx — APPROVED** [review]

**Pull request merged**
