### PR TITLE
releng: Add option for silent setup

### PR DESCRIPTION
**Pull request by yaqwsx**

### CODE REVIEW

**Review by Ondraceq — COMMENTED** [review]
I was thinking about redirecting the error output into stderr (e.g. by `>&2 echo "error"`)
(and I think that if you don't specify `-h`, you should get the help at stderr as well - e.g. for when redirecting to a file)

Theoretically if you use the stdin and stderr correctly, you could get rid of the `silentEcho` - and solve it by redirecting the file descriptors. But it would probably have some problems (e.g. on teardown).

**Comment by Ondraceq** [comment]
Do you know why the checks weren't successful? I don't know how to read it from the output.

**Comment by yaqwsx** [comment]
Github Actions had problems that day and the runs died randomly. If I rerun them, they should pass.

**Comment by yaqwsx** [comment]
I agree. I just squashed the changes in a single commit. The reason for being explicitly silent is when it is used inside Surveryor.

**Review by Ondraceq — APPROVED** [review]

**Pull request merged**
