### PR TITLE
rofisim: Update names in module sdf

### PR DESCRIPTION
**Pull request by Ondraceq**
This commit removes the name collision in gazebo11 and synchronizes the RoFI module joints to appear in the right order in Gazebo client.

### CODE REVIEW

**Comment by yaqwsx** [comment]
Why did `data/gazebo/worlds/two_modules.world` disappear? Otherwise, I approve.

**Comment by Ondraceq** [comment]
> 
> Why did `data/gazebo/worlds/two_modules.world` disappear? 

It felt like a consistency burden. The same file is built from `examples/basicMove.in`.
But thinking about it, it might be good to have `two_modules` in the `worlds` folder as well. Do you think it's better to have it in the `.in` or the generated `.world`?

I didn't realize that you can build specific targets - so maybe the generated file makes sense.

**Comment by yaqwsx** [comment]
I would say it would be nice to **not** have the generated files in the directory but instead, build them.

**Comment by Ondraceq** [comment]
The `two_modules.in` file is the same as `examples/basicMove.in`, but for me it makes sense to have the file in both locations (and it's four lines).

**Review by yaqwsx — APPROVED** [review]
Ok

**Pull request merged**
