### PR TITLE
Branches docs

### PR DESCRIPTION
**Pull request by Ondraceq**

### CODE REVIEW

**Comment by yaqwsx** [comment]
Also, put `set -x` into the shell command to see which statement actually failed - I think it is the second `git fetch --all`

**Comment by Ondraceq** [comment]
> Also, put `set -x` into the shell command to see which statement actually failed - I think it is the second `git fetch --all`

The 20be0b1 is without the second `fetch --all`

**Comment by Ondraceq** [comment]
I tried the version from 73ff5fd at cb0d2c0 but it failed

**Comment by Ondraceq** [comment]
It's interesting that the commit ci succeded, but the branch ci failed...

**Pull request closed without merging**
